"""add_full_name

Revision ID: 37e7bcc52265
Revises: ac395007ea55
Create Date: 2026-07-18 08:58:51.596460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37e7bcc52265'
down_revision: Union[str, None] = 'ac395007ea55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.add_column('customers', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.add_column('customers', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('customers', sa.Column('hashed_password', sa.String(length=200), nullable=True))
    op.add_column('customers', sa.Column('tier', sa.Enum('bronze', 'silver', 'gold', 'platinum', name='customertier'), nullable=True))
    op.add_column('customers', sa.Column('total_orders', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('total_spent_egp', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('role', sa.Enum('ADMIN', 'CUSTOMER', name='roleenum'), nullable=False))
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('customers', 'is_active')
    op.drop_column('customers', 'role')
    op.drop_column('customers', 'total_spent_egp')
    op.drop_column('customers', 'total_orders')
    op.drop_column('customers', 'tier')
    op.drop_column('customers', 'hashed_password')
    op.drop_column('customers', 'phone')
    op.drop_column('customers', 'full_name')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'CUSTOMER', name='roleenum'), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
