apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DATABASE_URL_SYNC: "postgresql://{{ .Values.database.postgresUser }}:{{ .Values.database.postgresPassword }}@{{ .Release.Name }}-postgres:5432/{{ .Values.database.postgresDb }}"
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.database.postgresUser }}:{{ .Values.database.postgresPassword }}@{{ .Release.Name }}-postgres:5432/{{ .Values.database.postgresDb }}"
  REDIS_URL: "redis://{{ .Release.Name }}-redis:6379/0"
  CELERY_BROKER_URL: "redis://{{ .Release.Name }}-redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://{{ .Release.Name }}-redis:6379/1"
