apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shippny-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ahmedgeeter/shiphny-ai-support.git'
    path: k8s/helm/shippny
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shippny-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
