backend:
  replicaCount: 2
  image:
    repository: "322824640926.dkr.ecr.us-east-1.amazonaws.com/shippny-backend"
    tag: "d7a052a810d20dde12ca55f78652b8048014cd46"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

worker:
  replicaCount: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

frontend:
  replicaCount: 2
  image:
    repository: "322824640926.dkr.ecr.us-east-1.amazonaws.com/shippny-frontend"
    tag: "d7a052a810d20dde12ca55f78652b8048014cd46"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: shippny.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend

# Use internal postgres/redis for now as a baseline
database:
  postgresUser: "postgres"
  postgresDb: "shippny_db"
  postgresPassword: "secure_postgres_password"
